# 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

$$
    % "boldsymbol"で太字にしている
    {A} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {c|cc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{c}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
            7 & 8 & -9 \\
        \end{array}\right] \quad
    {B} =
        \left[\begin{array}{c}
            % 横並びは&を挟む
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
        \end{array}\right] \quad
$$

行列積の求め方は、

$$
AB[0][0] = Ai0*B0j + Ai1*B1j + Ai2*B2j
$$

なので、

$$
AB[0][0] = (-1*0) + (2*0) + (3*2) = 6
$$

となる。

これをひとつずつ計算していく。


$$
AB[0][1] = (-1*2) + (2*2) + (3*9) = -2 + 4 + 27 = 29
$$

$$
AB[0][2] = (-1*1) + (2*-8) + (3*-1) = -1 + -16 + -3 = -20
$$

$$
AB[1][0] = (4*0) + (-5*0) + (6*2) = 0 + 0 + 12 = 12
$$

$$
AB[1][1] = (4*2) + (-5*2) + (6*9) = 8 + -10 + 54 = 52
$$

$$
AB[1][2] = (4*1) + (-5*-8) + (6*-1) = 4 + 40 + -6 = 38
$$

$$
AB[2][0] = (7*0) + (8*0) + (-9*2) = 0 + 0 + -18 = -18
$$

$$
AB[2][1] = (7*2) + (8*2) + (-9*9) = 14 + 16 + -81 = -51
$$

$$
AB[2][2] = (7*1) + (8*-8) + (-9*-1) = 7 + -64 + 9 = -48
$$

以上から、積ABは

$$
    \boldsymbol{AB} =
        \left[\begin{array}{c}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

となる。

# 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。



In [10]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# dot
c = np.dot(a_ndarray, b_ndarray)
print(c)

# matmul
d = np.matmul(a_ndarray, b_ndarray)
print(d)

# @
e = a_ndarray @ b_ndarray
print(e)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、計算を行ったかと思います。
この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [50]:
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
C = B.T # 転置行列を作成

row = np.shape(A)[0] # サイズを決定
col = np.shape(C)[0]

AB = np.zeros((row, col)) # 積AB行列を初期化


for i in range(row):
    element = [] # A*C で計算されるリストを格納するリストを宣言
    for j in range(col):
        element = A[i] * C[j] # ndarrayリストの掛け算
        #print(sum(element))
        AB[i][j] = sum(element) # リストの合計値を行列ABのi,jに格納
print(AB)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

In [61]:
import numpy as np


def matrix_product(a, b):
    c = b.T
    row = np.shape(a)[0]
    col = np.shape(c)[0]
    if row == col:
        AB = np.zeros((row, col))
    
        for i in range(row):
            element = []
            for j in range(col):
                element = a[i] * c[j]
                AB[i][j] = sum(element)
        return AB
    else:
        print("row :" + str(row))
        print("col :" + str(col))
        print("can not calculation")
        


def main():
    a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]]) # ここの行列を変えれば結果が変わる
    b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
    
    #テスト
    #a = np.array([[5, 1, 0], [2, 2, 1], [-8, 1, -9]])
    #b = np.array([[0, 2], [4, 1], [-2, 0]])
    print(matrix_product(a,b))

if __name__ == '__main__':
    main()

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。



In [68]:
import numpy as np


def matrix_product(a, b):
    c = b.T
    row = np.shape(a)[0]
    col = np.shape(c)[0]
    if row == col:
        AB = np.zeros((row, col))
    
        for i in range(row):
            element = []
            for j in range(col):
                element = a[i] * c[j]
                AB[i][j] = sum(element)
        return AB
    else: # 行と列のサイズが合っていない場合は計算せず終了させる
        print("A row : " + str(row))
        print("B col : " + str(col))
        print("can not calculation")
        


def main():
    #a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]]) # ここの行列を変えれば結果が変わる
    #b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
    
    # 行と列をずらす
    a = np.array([[5, 1, 0], [2, 2, 1], [-8, 1, -9]])
    b = np.array([[0, 2], [4, 1], [-2, 0]])
    print(matrix_product(a,b))

if __name__ == '__main__':
    main()

A row : 3
B col : 2
can not calculation
None


# 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

※すでに転置で回答したので、転置ではないverを記載します。

In [69]:
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

row = np.shape(A)[0] # サイズを決定
col = np.shape(B)[1]

AB = np.zeros((row, col)) # 積AB行列を初期化


for i in range(row):
    element = [] # A*C で計算されるリストを格納するリストを宣言
    for j in range(col):
        element = A[i] * B[:,j] # ndarrayリストの掛け算
        #print(sum(element))
        AB[i][j] = sum(element) # リストの合計値を行列ABのi,jに格納
print(AB)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
